kind: Service                             
apiVersion: v1
metadata:
  name: webapp-deployment
  labels:
    app: webapp-deployment
spec:
  ports:
    - port: 80                        
      targetPort: 8080
      nodePort: 32145
  selector:
    app: webapp-deployment                    
  type: LoadBalancer 
